adm/urls.py
# adm/urls.py
from django.urls import re_path
from . import (adm_main, adm_cliente, adm_producto, adm_trabajador, adm_trabajo, adm_categoria,
               adm_vitrina, adm_venta, adm_registroventa, adm_gastonooperativo)

urlpatterns = [
    re_path(r'^$', adm_main.view, name='adm_main'),
    re_path(r'^adm_venta$', adm_venta.view, name='adm_venta'),
    re_path(r'^adm_venta/registroventa$', adm_registroventa.view, name='registroventa'),
    re_path(r'^administracion/clientes$', adm_cliente.view, name='clientes'),
    re_path(r'^administracion/trabajadores$', adm_trabajador.view, name='trabajadores'),
    re_path(r'^administracion/productos$', adm_producto.view, name='productos'),
    re_path(r'^administracion/productos/kardex$', adm_producto.view, name='kardex'),
    re_path(r'^administracion/categorias$', adm_categoria.view, name='categorias'),
    re_path(r'^administracion/trabajos$', adm_trabajo.view, name='trabajos'),
    re_path(r'^administracion/vitrinas', adm_vitrina.view, name='vitrinas'),
    re_path(r'^administracion/gastosnooperativos', adm_gastonooperativo.view, name='gastonooperativo'),
]

mecanica/urls.py
# project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adm.urls')),
]

adm/models.py
from django.db import models
from django.db.models import Model

from core.models import ModeloBase, Persona


# Create your models here.
class Cliente(ModeloBase):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, verbose_name=u'Persona', related_name='personacliente')
    deuda_pendiente = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name=u'Deuda del cliente')

    def __str__(self):
        return f'<li>{self.persona}</li> <li>DEBE: <b style="color: salmon">${self.deuda_pendiente}</b></li>'

class Trabajador(ModeloBase):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE,verbose_name=u'Persona', related_name='personatrabajador', blank=True, null=True)
    sueldo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=u'Sueldo del trabajador')

    def __str__(self):
        return f'{self.persona} - ${self.sueldo}'

class Categoria(ModeloBase):
    nombre = models.CharField(max_length=500, blank=True, null=True, verbose_name=u'Nombre de la Categoría')

    def __str__(self):
        return self.nombre

class Subcategoria(ModeloBase):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='subcategoria', verbose_name=u'Nombre de la Categoría')
    nombre = models.CharField(max_length=500, blank=True, null=True, verbose_name=u'Nombre de la Subcategoria')

    def __str__(self):
        return f'{self.categoria} - {self.nombre}'


class Vitrina(ModeloBase):
    codigo = models.CharField(max_length=500, blank=True, null=True, verbose_name=u'Código de la Vitrina')

    def __str__(self):
        return f'{self.codigo}'

class Producto(ModeloBase):
    nombre = models.CharField(max_length=500, blank=True, null=True, verbose_name=u'Nombre del Producto')
    subcategoria = models.ForeignKey(Subcategoria, on_delete=models.CASCADE, related_name='productos', blank=True, null=True)
    vitrina = models.ForeignKey(Vitrina, on_delete=models.CASCADE, blank=True, null=True, related_name='producto_vitrina', verbose_name=u'Vitrina')
    descripcion = models.CharField(max_length=2000, blank=True, null=True, verbose_name=u'Descripción del producto')

    def __str__(self):
        return f'{self.id} - {self.nombre}'

    def get_cantidad_lote(self, lote_id):
        """Calcula la cantidad actual disponible para un lote específico desde el kardex"""
        entrada = KardexProducto.objects.filter(producto=self, lote_id=lote_id, tipo_movimiento=1).aggregate(total=models.Sum('cantidad'))['total'] or 0

        salida = KardexProducto.objects.filter(producto=self, lote_id=lote_id, tipo_movimiento=2).aggregate(total=models.Sum('cantidad'))['total'] or 0

        return entrada - salida

    def lote_actual(self):
        """Devuelve el lote actual con stock disponible."""
        return LoteProducto.objects.filter(producto=self, cantidad__gt=0).order_by('fecha_adquisicion').first()

class LoteProducto(ModeloBase):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name=u'Producto', related_name='loteproducto')
    cantidad = models.IntegerField(blank=True, null=True, verbose_name=u'Cantidad')
    precioventa = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=u'Precio de Venta')
    preciocompra = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=u'Precio de Compra')
    fecha_adquisicion = models.DateTimeField(null=True, blank=True, verbose_name=u'Fecha de ingreso')

    def __str__(self):
        return f"LOTE {self.id} - {self.producto.nombre} - ${self.preciocompra}"

TIPO_MOVIMIENTO = (
    (1, u'COMPRA'),
    (2, u'VENTA'),
    (3, u'CANCELADO')
)

class KardexProducto(ModeloBase):
    producto = models.ForeignKey(Producto, verbose_name=u'Producto', related_name='kardex_producto', on_delete=models.CASCADE)
    fecha_movimiento = models.DateTimeField(blank=True, null=True, verbose_name=u'Fecha del Movimiento', auto_now_add=True)
    tipo_movimiento = models.IntegerField(blank=True, null=True, default=1, choices=TIPO_MOVIMIENTO, verbose_name=u'Tipo de Movimiento')
    cantidad = models.IntegerField(blank=True, null=True, verbose_name=u'Cantidad')
    costo_unitario = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=2, verbose_name=u'Costo Unitario')
    precio_unitario = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=2, verbose_name=u'Precio Unitario')
    costo_total = models.DecimalField(blank=True, null=True, max_digits=12, decimal_places=2, verbose_name=u'Costo Total')
    saldo_cantidad = models.IntegerField(blank=True, null=True, verbose_name=u'Saldo Cantidad')
    # saldo_costo = models.DecimalField(blank=True, null=True, max_digits=12, decimal_places=2, verbose_name=u'Saldo Costo')
    # saldo_ganancia = models.DecimalField(blank=True, null=True, max_digits=12, decimal_places=2, verbose_name=u'Saldo Ganancia')
    # observacion = models.CharField(max_length=500, blank=True, null=True, verbose_name=u'Observación')
    lote = models.ForeignKey(LoteProducto, on_delete=models.CASCADE, blank=True, null=True, verbose_name=u'Lote')

    def __str__(self):
        return f'KARDEX DE {self.producto.nombre} - {self.fecha_movimiento}'

    def save(self, *args, **kwargs):
        ultimo_kardex = KardexProducto.objects.filter(producto=self.producto).order_by('-id').first()

        saldo_cantidad_anterior = ultimo_kardex.saldo_cantidad if ultimo_kardex else 0

        self.costo_total = self.cantidad * self.costo_unitario

        if self.tipo_movimiento == 1 or self.tipo_movimiento == 3:
            self.saldo_cantidad = saldo_cantidad_anterior + self.cantidad
        elif self.tipo_movimiento == 2:
            self.saldo_cantidad = saldo_cantidad_anterior - self.cantidad

        super(KardexProducto, self).save(*args, **kwargs)

class Trabajo(ModeloBase):
    nombre = models.CharField(max_length=500, blank=True, null=True, verbose_name=u'Nombre de Trabajo')
    precio = models.DecimalField(default=0, max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=u'Precio del Trabajo')
    detalle = models.CharField(max_length=5000, blank=True, null=True, verbose_name=u'Detalle del Trabajo')

    def __str__(self):
        return f'{self.nombre}'

class GastoNoOperativo(ModeloBase):
    titulo = models.CharField(blank=True, null=True, max_length=500, verbose_name=u'Titulo del Gasto')
    detalle = models.CharField(blank=True, null=True, verbose_name=u'Titulo del Gasto', max_length=2000)
    valor = models.DecimalField(default=0, max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=u'Valor del Gasto')

    def __str__(self):
        return f'{self.titulo} - ${self.valor}'

ESTADO_VENTA = (
    (0, u'TODO'),
    (1, u'PENDIENTE'),
    (2, u'PAGADO')
)

class Venta(ModeloBase):
    fecha_venta = models.DateTimeField(blank=True, null=True, verbose_name=u'Fecha de Venta')
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, blank=True, null=True, verbose_name=u'Nombre del Cliente', related_name='trabajos')
    descuento = models.DecimalField(default=0, max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=u'Descuento')
    totalventa = models.DecimalField(default=0, max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=u'Precio Total')
    subtotalventa = models.DecimalField(default=0, max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=u'Subtotal')
    detalle = models.CharField(max_length=5000, blank=True, null=True, verbose_name=u'Detalle del Trabajo')
    abono = models.DecimalField(default=0, max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=u'Abono')
    estado = models.IntegerField(default=1, choices=ESTADO_VENTA, blank=True, null=True, verbose_name=u'Estado de la Venta')

    def __str__(self):
        return f'#{self.id} - {self.get_estado_display()} - ${self.totalventa}'

    def obtener_detalles(self):
        detalles = []

        # Obtener detalles de productos
        for detalle in self.detalleproducto.all():
            detalles.append(f"<li><b>{detalle.producto.nombre}</b> x <b>{detalle.cantidad}</b> x <b>${detalle.preciounitario}</b></li>")

        # Obtener detalles de servicios
        for detalle in self.detalleservicio.all():
            detalles.append(f"<li><b>{detalle.servicio}</b> x <b>{detalle.cantidad}</b> x <b>${detalle.total}</b></li>")

        # Obtener detalles adicionales
        for detalle in self.detalleadicional.all():
            detalles.append(f"<li><b>{detalle.detalle}</b> x <b>${detalle.precio}</b></li>")

        return "\n".join(detalles)

    def obtener_detalles_excel(self):
        detalles = []

        # Obtener detalles de productos
        for detalle in self.detalleproducto.all():
            detalles.append(f"{detalle.producto.nombre} x {detalle.cantidad} x ${detalle.preciounitario}")

        # Obtener detalles de servicios
        for detalle in self.detalleservicio.all():
            detalles.append(f"{detalle.servicio} x {detalle.cantidad} x ${detalle.total}")

        # Obtener detalles adicionales
        for detalle in self.detalleadicional.all():
            detalles.append(f"{detalle.detalle} x ${detalle.precio}")

        return "\n".join(detalles)

    def obtener_deuda(self):
        return f'<b style="color: salmon">${self.totalventa - self.abono}</b>'

class VentaProductoDetalle(ModeloBase):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE, blank=True, null=True, verbose_name=u'Venta', related_name='detalleproducto')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, verbose_name=u'Producto', related_name='productoventa')
    lote = models.ForeignKey(LoteProducto, on_delete=models.CASCADE, verbose_name=u'Lote', related_name='detalleventa')

templates/venta/view.html
{% extends 'base_dashboard.html' %}
{% block extrahead %}
    <script>
        $(function () {
            const table = $('#dataTable').DataTable();
            table.order([0, 'desc']).draw();
            const $estado = $('#id_estado');
            $estado.select2()
        })
    </script>
{% endblock %}
{% block dashboard %}
    <div class="container-fluid">
        <div class="card mb-4 py-1 border-left-info">
            <div class="card-body" style="display: flex; justify-content: space-between">
                <a href="{% url 'registroventa' %}" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50"><i class="fas fa-plus"></i></span>
                    <span class="text">Registrar Venta</span>
                </a>

                <div style="width: 40%">
                    <form method="GET" action="{% url 'adm_venta' %}"
                          style="display: flex; flex-direction: row; gap: 10px">
                        <a href="{{ request.path }}?action=excelfechaestado&fecha={{ fechafiltro }}&estado={{ estadofiltro }}" class="btn btn-success btn-icon-split" style="width: 100px">
                            <span style="width: 100%" class="icon text-white-50"><i class="fas fa-file-excel"></i></span>
                        </a>
                        <input type="date" name="fechafiltro" value="{{ fechafiltro }}" class="form-control" onchange="this.form.submit()">
                        <select name="estado" id="id_estado" onchange="this.form.submit()">
                            {% for opcion in opciones %}
                                <option value="{{ opcion.0 }}" {% if request.GET.estado == opcion.0|stringformat:"s" %}selected{% endif %}>{{ opcion.1 }}</option>
                            {% endfor %}
                        </select>
                        <a href="{% url 'adm_venta' %}" class="btn btn-info btn-icon-split" style="width: 100px">
                            <span class="icon text-white-50"><i class="fas fa-sync"></i></span>
                        </a>
                    </form>

                </div>

            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th style="width: .1%">ID</th>
                            <th style="width: 2%">Detalle</th>
                            <th style="width: .5%">Fecha</th>
                            <th style="width: .8%">Cliente</th>
                            <th style="width: .1%">Abono</th>
                            <th style="width: .1%">Subtotal</th>
                            <th style="width: .1%">Descuento</th>
                            <th style="width: .1%">Total</th>
                            <th style="width: .1%;">Estado</th>
                            <th style="width: .2%"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for l in list %}
                            <tr>
                                <td>{{ l.id }}</td>
                                <td style="font-size: 12px">{{ l.obtener_detalles|safe }}</td>
                                <td>{{ l.fecha_venta|date:"d-m-Y" }}</td>
                                <td style="font-size: 12px">{{ l.cliente|default_if_none:""|safe }}</td>
                                <td style="color:{% if l.abono == 0 %}salmon{% elif l.abono == l.totalventa %}#1cc88a{% else %}#2e59d9{% endif %}"><b>${{ l.abono }}</b></td>
                                <td>${{ l.subtotalventa }}</td>
                                <td>${{ l.descuento }}</td>
                                <td style="color: salmon"><b>${{ l.totalventa }}</b></td>
                                <td style="color:{% if l.estado == 1 %}salmon{% elif l.estado == 2 %}#1cc88a{% endif %}"><b>{{ l.get_estado_display }}</b></td>
                                <td style="text-align: center">
                                    <div class="dropdown no-arrow">
                                        <a class="dropdown-toggle" href="#" role="button"
                                           id="dropdownMenuLink"
                                           data-toggle="dropdown" aria-haspopup="true"
                                           aria-expanded="false">
                                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                             aria-labelledby="dropdownMenuLink">
                                            <div class="dropdown-header">Acciones:</div>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="{% url 'registroventa' %}?action=edit&id={{ l.id }}" style="display: flex; align-items: center;">
                                                <span class="icon text-gray-600" style="width: 15px; height: 15px; margin-right: 10px; display: flex; align-items: center; justify-content: center;"><i class="fas fa-edit"></i></span>
                                                <span class="text" style="flex-grow: 1;">Editar</span>
                                            </a>
                                            <a class="dropdown-item" href="javascript:void(0);"
                                               onclick="eliminarajax('{{ l.id }}', '{{ l }}', 'cancelarventa')"
                                               style="display: flex; align-items: center;">
                                                <span class="icon text-gray-600" style="width: 15px; height: 15px; margin-right: 10px; display: flex; align-items: center; justify-content: center;"><i class="fas fa-ban"></i></span>
                                                <span class="text" style="flex-grow: 1;">Cancelar Venta</span>
                                            </a>
                                            {% if l.estado == 1 %}
                                                <a class="dropdown-item id_generarfactura" href="javascript:void(0);" style="display: flex; align-items: center;" onclick="formModal('{{ l.id }}', 'PENDIENTE: {{ l.obtener_deuda }}', 'abonardeuda', true, '')">
                                                    <span class="icon text-gray-600"
                                                          style="width: 15px; height: 15px; margin-right: 10px; display: flex; align-items: center; justify-content: center;">
                                                        <i class="fas fa-plus"></i>
                                                    </span>
                                                    <span class="text" style="flex-grow: 1;">Abonar</span>
                                                </a>
                                            {% endif %}
                                            <a class="dropdown-item id_generarfactura" href="{{ request.path }}?action=generarfacturapdf&id={{ l.id }}" style="display: flex; align-items: center;">
                                                <span class="icon text-gray-600" style="width: 15px; height: 15px; margin-right: 10px; display: flex; align-items: center; justify-content: center;"><i class="fas fa-file-pdf"></i></span>
                                                <span class="text" style="flex-grow: 1;">Nota Venta</span>
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}