adm/urls.py
# adm/urls.py
from django.urls import re_path
from . import (adm_main, adm_cliente, adm_producto, adm_trabajador, adm_trabajo, adm_categoria,
               adm_vitrina, adm_venta, adm_registroventa, adm_gastonooperativo)

urlpatterns = [
    re_path(r'^$', adm_main.view, name='adm_main'),
    re_path(r'^adm_venta$', adm_venta.view, name='adm_venta'),
    re_path(r'^adm_venta/registroventa$', adm_registroventa.view, name='registroventa'),
    re_path(r'^administracion/clientes$', adm_cliente.view, name='clientes'),
    re_path(r'^administracion/trabajadores$', adm_trabajador.view, name='trabajadores'),
    re_path(r'^administracion/productos$', adm_producto.view, name='productos'),
    re_path(r'^administracion/productos/kardex$', adm_producto.view, name='kardex'),
    re_path(r'^administracion/categorias$', adm_categoria.view, name='categorias'),
    re_path(r'^administracion/trabajos$', adm_trabajo.view, name='trabajos'),
    re_path(r'^administracion/vitrinas', adm_vitrina.view, name='vitrinas'),
    re_path(r'^administracion/gastosnooperativos', adm_gastonooperativo.view, name='gastonooperativo'),
]

mecanica/urls.py
# project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adm.urls')),
]

adm/forms.py
from email.policy import default

from django import forms
from django.db.models import Exists, OuterRef
from django.contrib.admin.widgets import AutocompleteSelect
from core.models import Persona
from core.modeloform import FormModeloBase
from .models import Trabajo, Trabajador, Cliente, Categoria, Vitrina, Subcategoria, Producto, LoteProducto

class AddTrabajoForm(FormModeloBase):
    trabajo = forms.ModelChoiceField(label=u'Trabajo', queryset=Trabajo.objects.filter(status=True), required=True, widget=forms.Select(attrs={'col': '12', 'class': 'form-control'}))
    precio = forms.CharField(label=u'Precio Registrado', max_length=500, required=False, widget=forms.TextInput(attrs={'col': '12', 'class': 'form-control'}))
    nprecio = forms.DecimalField(label=u'Precio Personalizado', max_digits=10, decimal_places=2, required=False, widget=forms.NumberInput(attrs={'decimal': '2', 'col':'12', 'separator': 'true',"separatortitle":'Opcional'}))
    trabajador = forms.ModelChoiceField(label=u'Trabajador', queryset=Trabajador.objects.filter(status=True), required=False, widget=forms.Select(attrs={'col': '12', 'class': 'form-control'}))
    cliente = forms.ModelChoiceField(label=u'Cliente', queryset=Cliente.objects.filter(status=True), required=False, widget=forms.Select(attrs={'col': '12', 'class': 'form-control'}))
    detalle = forms.CharField(label=u'Detalle', required=False, widget=forms.Textarea(attrs={'rows': '3', 'placeholder': 'Detalle del Trabajo', 'class': 'form-control'}))

class TrabajoDiaForm(FormModeloBase):
    trabajo = forms.ModelChoiceField(label=u'Trabajo', queryset=Trabajo.objects.filter(status=True), required=True, widget=forms.Select(attrs={'col': '6', 'class': 'form-control'}))
    precio = forms.DecimalField(label=u'Precio', max_digits=10, decimal_places=2, required=True, widget=forms.NumberInput(attrs={'decimal': '2', 'col':'6', 'placeholder': 'Precio del Trabajo'}))
    trabajador = forms.ModelChoiceField(label=u'Trabajador', queryset=Trabajador.objects.filter(status=True), required=False, widget=forms.Select(attrs={'col': '6', 'class': 'form-control'}))
    cliente = forms.ModelChoiceField(label=u'Cliente', queryset=Cliente.objects.filter(status=True), required=False, widget=forms.Select(attrs={'col': '6', 'class': 'form-control'}))
    detalle = forms.CharField(label=u'Detalle', required=False, widget=forms.Textarea(attrs={'rows': '3', 'placeholder': 'Detalle del Trabajo', 'class': 'form-control'}))

class TextoForm(FormModeloBase):
    texto = forms.CharField(max_length=500, required=True, widget=forms.TextInput(attrs={'col': '12', 'class': 'form-control'}))

class DecimalForm(FormModeloBase):
    decimal = forms.DecimalField(max_digits=10, decimal_places=2, required=True, widget=forms.NumberInput(attrs={'decimal': '2', 'col':'12'}))

class SubcategoriaForm(FormModeloBase):
    categoria = forms.ModelChoiceField(queryset=Categoria.objects.filter(status=True), required=True, widget=forms.Select(attrs={'col': '12', 'class': 'form-control'}))
    subcategoria = forms.CharField(max_length=500, required=True, widget=forms.TextInput(attrs={'col': '12', 'class': 'form-control'}))

class ProductoForm(FormModeloBase):
    nombre = forms.CharField(label=u'Nombre', max_length=500, required=True, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Nombre del Producto'}))
    cantidad = forms.IntegerField(label=u'Cantidad', required=True, widget=forms.NumberInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Cantidad de Productos ingresados'}))
    preciocompra = forms.DecimalField(label=u'Precio Compra (unidad)', max_digits=10, decimal_places=2, required=True, widget=forms.NumberInput(attrs={'decimal': '2', 'col':'6', 'placeholder': 'Precio del Producto'}))
    precioventa = forms.DecimalField(label=u'Precio Venta (unidad)', max_digits=10, decimal_places=2, required=True, widget=forms.NumberInput(attrs={'decimal': '2', 'col':'6', 'placeholder': 'Precio del Producto'}))
    vitrina = forms.ModelChoiceField(label=u'Vitrina', queryset=Vitrina.objects.filter(status=True), required=False, widget=forms.Select(attrs={'col': '6', 'class': 'form-control', 'separator': 'true',"separatortitle":'Detalle del producto'}))
    subcategoria = forms.ModelChoiceField(label=u'Subcategoria', queryset=Subcategoria.objects.filter(status=True), required=False, widget=forms.Select(attrs={'col': '6', 'class': 'form-control'}))
    descripcion = forms.CharField(label=u'Descripción', max_length=2000, required=False, widget=forms.Textarea(attrs={'rows': '3', 'placeholder': 'Descripcion del Producto', 'class': 'form-control'}))

class AumentarProductoForm(FormModeloBase):
    cantidad = forms.IntegerField(label=u'Cantidad', required=True, widget=forms.NumberInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Cantidad a aumentar'}))
    preciocompra = forms.DecimalField(label=u'Precio Compra', max_digits=10, decimal_places=2, required=False, widget=forms.NumberInput(attrs={'decimal': '2', 'col':'6', 'placeholder': 'Precio de Compra'}))
    precioventa = forms.DecimalField(label=u'Precio Venta', max_digits=10, decimal_places=2, required=False, widget=forms.NumberInput(attrs={'decimal': '2', 'col':'6', 'placeholder': 'Precio de Venta'}))

class TrabajoForm(FormModeloBase):
    nombre = forms.CharField(label=u'Nombre', max_length=500, required=True, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Nombre del Trabajo'}))
    precio = forms.DecimalField(label=u'Precio', max_digits=10, decimal_places=2, required=True, widget=forms.NumberInput(attrs={'decimal': '2', 'col':'6', 'placeholder': 'Precio del Trabajo'}))
    detalle = forms.CharField(label=u'Detalle', required=False, widget=forms.Textarea(attrs={'rows': '3', 'placeholder': 'Detalle del Trabajo', 'class': 'form-control'}))

class TrabajadorForm(FormModeloBase):
    cedula = forms.CharField(label=u'Cédula', max_length=10, required=True, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Cédula de Identidad'}))
    nombre = forms.CharField(label=u'Nombres', max_length=200, required=True, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Nombres'}))
    apellido1 = forms.CharField(label=u'Primer Apellido', max_length=200, required=True, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Apellido Paterno'}))
    apellido2 = forms.CharField(label=u'Segundo Apellido', max_length=200, required=False, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Apellido Materno'}))
    sueldo = forms.DecimalField(label=u'Sueldo', max_digits=10, decimal_places=2, min_value=0,required=True, widget=forms.NumberInput(attrs={'decimal': '2', 'col': '6', 'placeholder': 'Sueldo del trabajador'}))
    celular = forms.CharField(label=u'Teléfono ', max_length=10, required=False, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Número de Teléfono'}))
    direccion = forms.CharField(label=u'Dirección', max_length=200, required=False, widget=forms.TextInput(attrs={'col': '12', 'class': 'form-control', 'placeholder': 'Dirección de domicilio'}))
    correo = forms.CharField(label=u'Correo Electrónico', max_length=200, required=False, widget=forms.TextInput(attrs={'col': '12', 'class': 'form-control', 'placeholder': 'Email'}))


class ClienteForm(FormModeloBase):
    cedula = forms.CharField(label=u'Cédula', max_length=10, required=True, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Cédula de Identidad'}))
    nombre = forms.CharField(label=u'Nombres', max_length=200, required=True, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Nombres'}))
    apellido1 = forms.CharField(label=u'Primer Apellido', max_length=200, required=True, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Apellido Paterno'}))
    apellido2 = forms.CharField(label=u'Segundo Apellido', max_length=200, required=False, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Apellido Materno'}))
    direccion = forms.CharField(label=u'Dirección', max_length=200, required=False, widget=forms.TextInput(attrs={'col': '12', 'class': 'form-control', 'placeholder': 'Dirección de domicilio'}))
    celular = forms.CharField(label=u'Teléfono ', max_length=10, required=False, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Número de Teléfono'}))
    correo = forms.CharField(label=u'Correo Electrónico', max_length=200, required=False, widget=forms.TextInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Email'}))

class AddVentaForm(FormModeloBase):
    producto = forms.ModelChoiceField(label=u'Producto', queryset=Producto.objects.filter(status=True), required=True, widget=forms.Select(attrs={'col': '12', 'class': 'form-control'}))
    precio = forms.CharField(label=u'Precio Registrado', max_length=500, required=False, widget=forms.TextInput(attrs={'col': '12', 'class': 'form-control'}))
    cantidad = forms.IntegerField(label=u'Cantidad', initial=1, required=True, widget=forms.NumberInput(attrs={'col': '6', 'class': 'form-control', 'placeholder': 'Cantidad vendida'}))
    cliente = forms.ModelChoiceField(label=u'Cliente', queryset=Cliente.objects.filter(status=True), required=False, widget=forms.Select(attrs={'col': '12', 'class': 'form-control'}))
    nprecio = forms.DecimalField(label=u'Precio Personalizado', max_digits=10, decimal_places=2, required=False, widget=forms.NumberInput(attrs={'decimal': '2', 'col': '12', 'separator': 'true', "separatortitle": 'Opcional'}))
    trabajador = forms.ModelChoiceField(label=u'Trabajador', queryset=Trabajador.objects.filter(status=True), required=False, widget=forms.Select(attrs={'col': '12', 'class': 'form-control'}))

templates/modals/form.html
<input type="hidden" name="id" value="{{ id }}"/>
<input type="hidden" name="action" value="{{ action }}"/>

{% for field in form %}
    {% if field.field.widget.attrs.separator %}
        {% if field.field.widget.attrs.blanklinebefore %}
        {% endif %}
        <div style="width: 100%; height: max-content">
            <h6 style="width:100%; text-align:center; line-height:1em; margin:40px 0 10px; color: #b3b3b3">
                <span style="padding:0 10px; background: #fff;">
                    {% if field.field.widget.attrs.separatortitle %}
                        {{ field.field.widget.attrs.separatortitle }}
                    {% endif %}
                </span>
            </h6>
        </div>
    {% endif %}
    <div id="fieldset_{{ field.name }}" class="col-lg-{{ field.field.widget.attrs.col }}" style="float: left; padding-right: 10px;">
        {% if field.field.label %}
            <label class="control-label pr-2"
               for="id_{{ field.name }}"><b>{{ field.label }}</b>&nbsp;:
            </label>
        {% endif %}
        {{ field }}
        <p class="help-text">{{ field.help_text }} </p>
    </div>
{% endfor %}

{{ form.media|safe }}

<script>
    $(function () {
        $("select").select2({width: '100%'});
    });
</script>

templates/modals/form2.html
<input type="hidden" name="id" value="{{ id }}"/>
<input type="hidden" name="action" value="{{ action }}"/>

{% for field in form2 %}
    {% if field.field.widget.attrs.separator %}
        {% if field.field.widget.attrs.blanklinebefore %}
        {% endif %}
        <div style="width: 100%; height: max-content">
            <h6 style="width:100%; text-align:center; line-height:1em; margin:40px 0 10px; border-bottom: 1px solid #b3b3b3; color: #b3b3b3">
                <span style="padding:0 10px; background: #fff;">
                    {% if field.field.widget.attrs.separatortitle %}
                        {{ field.field.widget.attrs.separatortitle }}
                    {% endif %}
                </span>
            </h6>
        </div>
    {% endif %}
    <div id="fieldset_{{ field.name }}" class="col-lg-{{ field.field.widget.attrs.col }}" style="float: left; padding-right: 10px;">
        {% if field.field.label %}
            <label class="control-label pr-2"
               for="id_{{ field.name }}"><b>{{ field.label }}</b>&nbsp;:
            </label>
        {% endif %}
        {{ field }}
        <p class="help-text">{{ field.help_text }} </p>
    </div>
{% endfor %}

{{ form2.media|safe }}

<script>
    $(function () {
        $("select").select2({width: '100%'});
    });
</script>

templates/modals/form3.html
<input type="hidden" name="id" value="{{ id }}"/>
<input type="hidden" name="action" value="{{ action }}"/>

{% for field in form3 %}
    {% if field.field.widget.attrs.separator %}
        {% if field.field.widget.attrs.blanklinebefore %}
        {% endif %}
        <div style="width: 100%; height: max-content">
            <h6 style="width:100%; text-align:center; line-height:1em; margin:40px 0 10px; color: #b3b3b3">
                <span style="padding:0 10px; background: #fff;">
                    {% if field.field.widget.attrs.separatortitle %}
                        {{ field.field.widget.attrs.separatortitle }}
                    {% endif %}
                </span>
            </h6>
        </div>
    {% endif %}
    <div id="fieldset_{{ field.name }}" class="col-lg-{{ field.field.widget.attrs.col }}" style="float: left; padding-right: 10px;">
        {% if field.field.label %}
            <label class="control-label pr-2"
               for="id_{{ field.name }}"><b>{{ field.label }}</b>&nbsp;:
            </label>
        {% endif %}
        {{ field }}
        <p class="help-text">{{ field.help_text }} </p>
    </div>
{% endfor %}

{{ form3.media|safe }}

<script>
    $(function () {
        $("select").select2({width: '100%'});
    });
</script>

templates/modals/form4.html
<input type="hidden" name="id" value="{{ id }}"/>
<input type="hidden" name="action" value="{{ action }}"/>

{% for field in form4 %}
    {% if field.field.widget.attrs.separator %}
        {% if field.field.widget.attrs.blanklinebefore %}
        {% endif %}
        <div style="width: 100%; height: max-content">
            <h6 style="width:100%; text-align:center; line-height:1em; margin:40px 0 10px; color: #b3b3b3">
                <span style="padding:0 10px; background: #fff;">
                    {% if field.field.widget.attrs.separatortitle %}
                        {{ field.field.widget.attrs.separatortitle }}
                    {% endif %}
                </span>
            </h6>
        </div>
    {% endif %}
    <div id="fieldset_{{ field.name }}" class="col-lg-{{ field.field.widget.attrs.col }}" style="float: left; padding-right: 10px;">
        {% if field.field.label %}
            <label class="control-label pr-2"
               for="id_{{ field.name }}"><b>{{ field.label }}</b>&nbsp;:
            </label>
        {% endif %}
        {{ field }}
        <p class="help-text">{{ field.help_text }} </p>
    </div>
{% endfor %}

{{ form4.media|safe }}

<script>
    $(function () {
        $("select").select2({width: '100%'});
    });
</script>

templates/modals/form5.html
<input type="hidden" name="id" value="{{ id }}"/>
<input type="hidden" name="action" value="{{ action }}"/>

{% for field in form5 %}
    {% if field.field.widget.attrs.separator %}
        {% if field.field.widget.attrs.blanklinebefore %}
        {% endif %}
        <div style="width: 100%; height: max-content">
            <h6 style="width:100%; text-align:center; line-height:1em; margin:40px 0 10px; color: #b3b3b3">
                <span style="padding:0 10px; background: #fff;">
                    {% if field.field.widget.attrs.separatortitle %}
                        {{ field.field.widget.attrs.separatortitle }}
                    {% endif %}
                </span>
            </h6>
        </div>
    {% endif %}
    <div id="fieldset_{{ field.name }}" class="col-lg-{{ field.field.widget.attrs.col }}" style="float: left; padding-right: 10px;">
        {% if field.field.label %}
            <label class="control-label pr-2"
               for="id_{{ field.name }}"><b>{{ field.label }}</b>&nbsp;:
            </label>
        {% endif %}
        {{ field }}
        <p class="help-text">{{ field.help_text }} </p>
    </div>
{% endfor %}

{{ form5.media|safe }}

<script>
    $(function () {
        $("select").select2({width: '100%'});
    });
</script>

templates/modals/form_persona.html
<input type="hidden" name="id" value="{{ id }}"/>
<input type="hidden" name="action" value="{{ action }}"/>

{% for field in form %}
    {% if field.field.widget.attrs.separator %}
        {% if field.field.widget.attrs.blanklinebefore %}
        {% endif %}
        <div style="width: 100%; height: max-content">
            <h6 style="width:100%; text-align:center; line-height:1em; margin:40px 0 10px; color: #b3b3b3">
                <span style="padding:0 10px; background: #fff;">
                    {% if field.field.widget.attrs.separatortitle %}
                        {{ field.field.widget.attrs.separatortitle }}
                    {% endif %}
                </span>
            </h6>
        </div>
    {% endif %}
    <div id="fieldset_{{ field.name }}" class="col-lg-{{ field.field.widget.attrs.col }}"
         style="float: left; padding-right: 10px;">
        {% if field.field.label %}
            <label class="control-label pr-2"
                   for="id_{{ field.name }}"><b>{{ field.label }}</b>&nbsp;:
            </label>
        {% endif %}
        {{ field }}
        <p class="help-text">{{ field.help_text }} </p>
    </div>
{% endfor %}

{{ form.media|safe }}

<script>
    $(function () {
        $("select").select2({width: '100%'});

        $('#id_cedula').keyup(function () {
            var cedula = $(this).val()
            if (cedula.length === 10) {
                $.ajax({
                    type: 'GET',
                    url: '{{ request.path }}',
                    data: {'action': 'obtenercliente', 'cedula': cedula},
                    success: function (data) {
                        if (data.result === true) {
                            $('#id_nombre').val(data.data.nombre).attr('readonly', true)
                            $('#id_apellido1').val(data.data.apellido1).attr('readonly', true)
                            $('#id_apellido2').val(data.data.apellido2).attr('readonly', true)
                            $('#id_direccion').val(data.data.direccion).attr('readonly', true)
                            $('#id_celular').val(data.data.celular).attr('readonly', true)
                            $('#id_correo').val(data.data.correo).attr('readonly', true)
                        } else {
                            eliminarClienteModal()
                        }
                    }
                })
            } else {
                eliminarClienteModal()
            }
        });

        function eliminarClienteModal() {
            $('#id_nombre').val('').removeAttr('readonly', true)
            $('#id_apellido1').val('').removeAttr('readonly', true)
            $('#id_apellido2').val('').removeAttr('readonly', true)
            $('#id_direccion').val('').removeAttr('readonly', true)
            $('#id_celular').val('').removeAttr('readonly', true)
            $('#id_correo').val('').removeAttr('readonly', true)
        }
    });
</script>